/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.beerlib

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }

    fun beer(value: String) = "Drink $value"
}
